branches:
  only:
    - main

language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"


script:
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend victortyau/udagram-frontend:v1
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed victortyau/udagram-api-feed:v1
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user victortyau/udagram-api-user:v1
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag reverseproxy victortyau/reverseproxy:v1

after_script:
  - docker images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push victortyau/udagram-api-feed:v1
  - docker push victortyau/udagram-api-user:v1
  - docker push victortyau/udagram-frontend:v1
  - docker push victortyau/reverseproxy:v1
