branches:
  only:
    - main

language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"


script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed victortyau/udagram-api-feed:v1
  - docker images

after_script:
  - docker images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker image push victortyau/udagram-api-feed:v1
  - docker push victortyau/udagram-api-feed:v1
