apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  selector:
    matchLabels:
      service: reverseproxy
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - image: victortyau/reverseproxy:v1
        name: reverseproxy
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "2048Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
      restartPolicy: Always
